import { isSmallerScreen } from 'src/config';
import { StyleSheet } from 'react-native';

export const siteCardStyles = StyleSheet.create({
	outerContainer: {
		overflow: 'hidden',
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		width: isSmallerScreen ? '50%' : '33.3334%',
		aspectRatio: 0.861,
		height: 200,
	},
	touchable: {
		width: '100%',
		height: '100%',
		overflow: 'hidden',
		padding: isSmallerScreen ? 10 : 15,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
	},
	container: {
		width: '100%',
		height: '100%',
		borderRadius: 15,
		overflow: 'hidden',
		elevation: 5,
		alignItems: 'center',
		padding: isSmallerScreen ? 5 : 10,
		backgroundColor: 'background-basic-color-2',
		borderWidth: 2,
		borderStyle: 'solid',
		borderColor: 'color-basic-600',
	},
	heading: {
		paddingHorizontal: isSmallerScreen ? 5 : 10,
		paddingVertical: isSmallerScreen ? 10 : 15,
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	headingText: {
		fontWeight: '700',
		textTransform: 'capitalize',
		fontSize: isSmallerScreen ? 24 : 28,
	},
	cardContainer: {
		width: 100,
	},
	card: {
		backgroundColor: 'background-basic-color-1',
		borderRadius: 10,
		width: '100%',
		overflow: 'hidden',
		paddingVertical: isSmallerScreen ? 5 : 10,
		paddingHorizontal: 10,
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		fontWeight: 'bold',
		height: isSmallerScreen ? 45 : 50,
		elevation: 5,
		borderWidth: 2,
		borderStyle: 'solid',
		borderColor: 'color-basic-600',
	},
	cardValue: {
		color: 'text-basic-color',
		fontSize: isSmallerScreen ? 15 : 18,
	},
	cardIcon: {
		flexShrink: 0,
		flexGrow: 0,
		width: isSmallerScreen ? 30 : 35,
		height: '100%',
	},
	button: {
		position: 'absolute',
		bottom: isSmallerScreen ? 10 : 15,
		right: isSmallerScreen ? 10 : 15,
		width: 35,
		height: 35,
		borderRadius: 18,
		backgroundColor: 'background-basic-color-1',
		borderWidth: 1,
		padding: 5,
		borderStyle: 'solid',
		borderColor: 'color-basic-600',
	},
});
